name: Build APK and iOS

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli

      - name: Build APK
        run: |
          expo build:android --no-publish --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Add your Expo token to GitHub secrets

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli

      - name: Build iOS
        run: |
          expo build:ios --no-publish --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Add your Expo token to GitHub secrets
